after-login-command = ['exec-and-forget kitty --single-instance -d ~']

after-startup-command = ['exec-and-forget sketchybar --reload']

exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE']

start-at-login = true

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     5
    outer.top =        37
    outer.right =      10

[mode.main.binding]
    alt-t = 'exec-and-forget kitty --single-instance -d ~'

    alt-slash = 'layout tiles horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = ['mode service', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=service']
    alt-r = ['mode resize', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=resize']
    alt-a = ['mode launch', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=launch']

[mode.service.binding]
    esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main'] # reset layout
    f = ['layout floating tiling', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

    alt-shift-h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    alt-shift-j = ['join-with down', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    alt-shift-k = ['join-with up', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    alt-shift-l = ['join-with right', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

[mode.resize.binding]
    esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    f = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main', 'macos-native-fullscreen']
    m = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main', 'macos-native-minimize']
    minus = 'resize smart -50'
    shift-equal = 'resize smart +50'
    equal = 'balance-sizes'

[mode.launch.binding]
    esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    b = ['exec-and-forget open -n /Applications/qutebrowser.app', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    shift-b = ['exec-and-forget open -n /Applications/Firefox.app', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    f = ['exec-and-forget open ~', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    l = ['exec-and-forget open -n /System/Applications/Launchpad.app', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    m = ['exec-and-forget open -n /System/Applications/Mail.app', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    s = ['exec-and-forget open -n /System/Applications/System\ Settings.app', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    y = ['exec-and-forget kitty --single-instance -d ~ -e yazi', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

[[on-window-detected]]
    if.app-id = 'net.kovidgoyal.kitty'
    if.window-title-regex-substring = '^yazi$'
    run = ['layout floating']

[[on-window-detected]]
    if.app-name-regex-substring = '^mpv$'
    run = ['layout floating']
